<?xml version="1.0"?>

<!--
	definitions of some macros for easier description of the robot
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="link_box" params="link_name length width height density:=1 mesh_name:='nofile' *origin_vis *origin_col *origin_inertial">
    <xacro:property name="mass" value="${length*height*width*density}" />
    <link name="${link_name}">
      <visual>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_vis" />
        <geometry>
          <xacro:if value="${mesh_name == 'nofile'}">
            <box size="${length} ${width} ${height}"/>
          </xacro:if>
          <xacro:unless value="${mesh_name == 'nofile'}">
            <mesh filename="${mesh_name}" />
          </xacro:unless>
        </geometry>
      </visual>
      <collision>
        <!-- <origin xyz="0 0 0.0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_col" />
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_inertial" />
        <mass value="${mass}"/>
        <inertia
          ixx="${mass*(pow(height,2) + pow(width,2))/12}" ixy="0.0" ixz="0.0"
          iyy="${mass*(pow(length,2) + pow(height,2))/12}" iyz="0.0"
          izz="${mass*(pow(length,2) + pow(width,2))/12}"/>
      </inertial>
    </link>

    <gazebo reference="${link_name}_box">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />

      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>


      <!--kd  value="1.0" />
      <fdir1 value="1 0 0"/-->
      <material>gazebo/red</material>
    </gazebo>

  </xacro:macro>


  <xacro:macro name="link_cylinder" params="link_name radius length density:=1 mesh_name:='nofile' *origin_vis *origin_col *origin_inertial">
    <xacro:property name="mass" value="${pi*length*pow(radius,2)*density}" />
    <link name="${link_name}">
      <visual>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_vis" />
        <geometry>
          <xacro:if value="${mesh_name == 'nofile'}">
            <cylinder length="${length}" radius="${radius}"/>
          </xacro:if>
          <xacro:unless value="${mesh_name == 'nofile'}">
            <mesh filename="${mesh_name}" />
          </xacro:unless>
        </geometry>
      </visual>
      <collision>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_col" />
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <xacro:insert_block name="origin_inertial" />
        <mass value="${mass}"/>
        <inertia
          ixx="${mass*(3*pow(radius,2)+pow(length,2))/12}" ixy="0.0" ixz="0.0"
          iyy="${mass*(3*pow(radius,2)+pow(length,2))/12}" iyz="0.0"
          izz="${mass*pow(radius,2)/2}"/>
      </inertial>
    </link>

    <gazebo reference="${link_name}_cylinder">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />

      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>


      <!--kd  value="1.0" />
      <fdir1 value="1 0 0"/-->
      <material>Gazebo/blue</material>
    </gazebo>

  </xacro:macro>

</robot>
