<?xml version="1.0"?>
<robot name="rocuto" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files
  <xacro:include filename="$(find rocuto_pkg)/urdf/box.urdf.xacro" />
  <xacro:include filename="$(find rocuto_pkg)/urdf/cylinder.urdf.xacro" />
  <xacro:include filename="$(find rocuto_pkg)/urdf/sphere.urdf.xacro" />-->
  <xacro:include filename="$(find rocuto_pkg)/urdf/materials.xacro" />
  <xacro:include filename="$(find rocuto_pkg)/urdf/gazebo_rocuto.urdf.gazebo" />

  <!-- constants -->
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- frame properties -->
  <xacro:property name="frame_x_size" value="0.2" />
  <xacro:property name="frame_y_size" value="0.2" />
  <xacro:property name="frame_z_size" value="1" />
<!--<xacro:property name="mass" value="${length*height*width*density}" />-->

  <!-- link Properties -->
  <xacro:property name="link1_length" value="0.5" />
  <xacro:property name="link1_radius" value="0.1" />
  <!--<xacro:property name="mass" value="${length*2*radius*M_PI}" />-->

  <!-- tool Properties -->
  <xacro:property name="tool_length" value="0.1" />
  <xacro:property name="tool_width" value="0.5" />
  <xacro:property name="tool_height" value="0.1" />
<!--<xacro:property name="mass" value="${length*height*width*density}" />-->

  <!-- frame origin -->
  <xacro:property name="frame_x_origin" value="0" />
  <xacro:property name="frame_y_origin" value="0" />
  <xacro:property name="frame_z_origin" value="0.5" />

  <!-- joint 1 origin -->
  <xacro:property name="joint1_x" value="0" />
  <xacro:property name="joint1_y" value="${frame_y_size}" />
  <xacro:property name="joint1_z" value="0" />

  <!-- joint 2 origin -->
  <xacro:property name="joint2_x" value="${joint1_x}" />
  <xacro:property name="joint2_y" value="${joint1_y + 0.5}" />
  <xacro:property name="joint2_z" value="${joint1_z}" />

  <!-- joint 3 origin -->
  <xacro:property name="joint3_x" value="${joint1_x}" />
  <xacro:property name="joint3_y" value="${joint2_y + 0.5}" />
  <xacro:property name="joint3_z" value="${joint1_z}" />

<!-- ramme på robotplatform -->
  <link name="frame">
    <!--<pose>0 0 0.1 0 0 0</pose> POSE ER KANSKJE IKKE NØDVENDIG-->

    <collision>
      <origin xyz="${frame_x_origin} ${frame_y_origin} ${frame_z_origin}" rpy="0 0 0"/>
      <geometry>
        <box size="${frame_x_size} ${frame_y_size} ${frame_z_size}"/>
      </geometry>
    </collision>

    <visual name='frame_visual'>
    <origin xyz="${frame_x_origin} ${frame_y_origin} ${frame_z_origin}" rpy="0 0 0"/>
      <geometry>
        <box size="${frame_x_size} ${frame_y_size} ${frame_z_size}"/>
        <mesh filename="package://rocuto_pkg/meshes/link.stl"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="${frame_x_origin} ${frame_y_origin} ${frame_z_origin}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

<!-- link1 -->
  <link name="link1">
    <!--<pose>0 0 0.1 0 0 0</pose> POSE ER KANSKJE IKKE NØDVENDIG-->
    <collision>
      <origin xyz="${joint1_x} ${joint1_y} ${joint1_z}" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${joint1_x} ${joint1_y} ${joint1_z}" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
        <mesh filename="package://rocuto_pkg/meshes/link.stl"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
<origin xyz="${joint1_x} ${joint1_y} ${joint1_z}" rpy="${pi/2} 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

<!-- link2 -->
  <link name="link2">
    <!--<pose>0 0 0.1 0 0 0</pose>POSE ER KANSKJE IKKE NØDVENDIG-->
    <collision>
      <origin xyz="${joint2_x} ${joint2_y} ${joint2_z}" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${joint2_x} ${joint2_y} ${joint2_z}" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
        <mesh filename="package://rocuto_pkg/meshes/link.stl"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="${joint2_x} ${joint2_y} ${joint2_z}" rpy="${pi/2} 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

<!-- tool -->
  <link name="tool">
    <!--<pose>0 0 0.1 0 0 0</pose>POSE ER KANSKJE IKKE NØDVENDIG-->
    <collision>
      <origin xyz="${joint3_x} ${joint3_y} ${joint3_z}" rpy="0 0 0"/>
      <geometry>
        <box size="${tool_length} ${tool_width} ${tool_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${joint3_x} ${joint3_y} ${joint3_z}" rpy="0 0 0"/>
      <geometry>
        <box size="${tool_length} ${tool_width} ${tool_height}"/>
        <mesh filename="package://rocuto_pkg/meshes/frame_visual.dae"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="${joint3_x} ${joint3_y} ${joint3_z}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

<!-- leddet mellom ramme og link1 -->
  <joint name="link1_to_link2" type="revolute">
    <origin xyz="${joint1_x} ${joint1_y} ${joint1_z}" rpy="0 0 0"/>
    <parent link="link1"/>
    <child link="link2"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100" velocity="100" lower="-${pi}" upper="${pi}"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

<!-- leddet mellom link1 og link2 -->
  <joint name="frame_to_link1" type="revolute">
    <origin xyz="${joint2_x} ${joint2_y} ${joint2_z}" rpy="0 0 0"/>
    <parent link="frame"/>
    <child link="link1"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100" velocity="100" lower="-${pi}" upper="${pi}"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

<!-- Dette er ikke et ledd bare kobling mellom link2 og tool -->
  <joint name="link2_to_tool" type="fixed">
    <origin xyz="${joint3_x} ${joint3_y} ${joint3_z}" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="tool"/>
    <!--axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/-->
  </joint>

  <transmission name="link1_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="frame_to_link1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="link1_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="link2_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="link1_to_link2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="link2_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
