rocuto:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller
  link1:
    type: position_controllers/JointPositionController
    joint: frame_to_link1

  # Controller
  link2:
    type: position_controllers/JointPositionController
    joint: link1_to_link2

  # # Controller
  # arm_controller:
  # type: joint_state_controller/JointTradjectoryController
  # joints:
  # - frame_to_link1
  # - link1_to_link2